### PR TITLE
Detect closed connections

### PR DESCRIPTION
**Pull request by andig**
Refs https://github.com/philippseith/signalr/issues/66

### CODE REVIEW

**Comment by andig** [comment]
~~I'm not too happy with this solution, but my feeling is anything bigger would require a refactoring.~~

As for the imports order: it seems that VSCode should be using `gofmt`, I suspect Goland does something non-standard?

**Comment by andig** [comment]
Coverage test errors due to

    Please provide an upload token from codecov.io with valid arguments

**Comment by philippseith** [comment]
> Coverage test errors

Yes, I know (and I am unhappy). Coverage upload does not work for forks.

**Comment by andig** [comment]
I've just realized we might have made this a `chan error`. That could still be closed to indicate connection end. Unless there's any need to signal errors we could leave this as-is. If you see a good use case I could change it once more. A `chan error` would mean that we should only do non-blocking sends!

**Comment by philippseith** [comment]
All client  methods (except Start/Stop) are non blocking.
Which error would you push to the channel? Currently loop.Run does not return an error, but I can already see how this could be changed.

**Comment by philippseith** [comment]
@andig see https://github.com/philippseith/signalr/pull/70

**Pull request merged**
