### PR TITLE
Fix most linter errors

### PR DESCRIPTION
**Pull request by andig**
Breaking change: capitalizes `WithHTTPServeMux`

### CODE REVIEW

**Comment by philippseith** [comment]
which linter did you use? I am running golangci-lint from time to time.

**Comment by andig** [comment]
Yes, me too. Just calling

    make lint

**Comment by philippseith** [comment]
ah, that's from the old times. It is still calling golint instead of golangci-lint. I will change this.

**Comment by andig** [comment]
The changes should still be ok and `HTTP` spelling currently is inconsistent. 

fyi:

```
❯ golangci-lint run ./...
chatsample/middleware/response_writer_wrapper.go:45:2: S1023: redundant `return` statement (gosimple)
	return
	^
chatsample/main.go:151:17: lostcancel: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
			creationCtx, _ := context.WithTimeout(context.Background(), 2*time.Second)
			             ^
```

**Comment by philippseith** [comment]
> fyi:

The golangci-lint run https://github.com/philippseith/signalr/runs/4084723025?check_suite_focus=true skips the chatsample because it is just a "useless" sample :-)

**Review by philippseith — APPROVED** [review]

**Pull request merged**
